// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadRecipe(arg1) {
  return window['go']['main']['App']['LoadRecipe'](arg1);
}

export function PrintRecipe(arg1, arg2) {
  return window['go']['main']['App']['PrintRecipe'](arg1, arg2);
}
