// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadRecipe(arg1:string):Promise<main.Recipe>;

export function PrintRecipe(arg1:main.Recipe,arg2:number):Promise<string>;
